-- =====================================================================
-- Projet 5 — API de Gestion d'un Inventaire de Produits
-- V1 : schéma initial
-- =====================================================================

CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Référence produit : identifiant métier unique.
    sku             VARCHAR(50)    NOT NULL,
    name            VARCHAR(200)   NOT NULL,
    description     TEXT,
    category        VARCHAR(50)    NOT NULL,
    -- Prix en décimal exact (jamais en virgule flottante).
    price           NUMERIC(10, 2) NOT NULL,
    current_stock   INTEGER        NOT NULL,
    -- Seuil déclenchant l'alerte de stock bas (5 unités par défaut).
    min_stock_level INTEGER        NOT NULL,
    max_stock_level INTEGER,
    unit            VARCHAR(20)    NOT NULL,
    status          VARCHAR(20)    NOT NULL,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED'))
);

-- Journal auditable de chaque variation de stock.
CREATE TABLE stock_movements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT      NOT NULL,
    movement_type   VARCHAR(20) NOT NULL,
    quantity        INTEGER     NOT NULL,
    quantity_before INTEGER     NOT NULL,
    quantity_after  INTEGER     NOT NULL,
    reason          TEXT,
    reference       VARCHAR(100),
    created_at      TIMESTAMP(6),
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_stock_movements_type CHECK (movement_type IN ('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER'))
);

CREATE TABLE stock_alerts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT      NOT NULL,
    alert_type  VARCHAR(20) NOT NULL,
    severity    VARCHAR(20) NOT NULL,
    message     TEXT,
    resolved    BOOLEAN     NOT NULL,
    resolved_at TIMESTAMP(6),
    created_at  TIMESTAMP(6),
    CONSTRAINT fk_stock_alerts_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_stock_alerts_type CHECK (alert_type IN ('LOW_STOCK', 'OUT_OF_STOCK', 'OVERSTOCK')),
    CONSTRAINT ck_stock_alerts_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

-- Les mouvements sont lus par produit, du plus récent au plus ancien.
CREATE INDEX idx_stock_movements_product ON stock_movements (product_id, created_at DESC);

-- Les alertes actives d'un produit sont relues à chaque mouvement de stock.
CREATE INDEX idx_stock_alerts_product_resolved ON stock_alerts (product_id, resolved);
